import type { NextPage } from "next";
import Head from "next/head";
import {
  BsCodeSlash,
  BsEmojiAngryFill,
  BsEmojiDizzyFill,
  BsEmojiExpressionlessFill,
  BsEmojiFrownFill,
  BsEmojiHeartEyesFill,
  BsEmojiLaughingFill,
  BsEmojiNeutralFill,
} from "react-icons/bs";
import styles from "../styles/Home.module.css";

import * as S from "../styles/header";

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Header Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.NavBar>
        <S.LogoContainer>LOGO</S.LogoContainer>
        <S.MenuContainer aria-label="menu-container">
          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiAngryFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>
            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="">
                <BsEmojiAngryFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem aria-label="menu-item">
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>

          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiDizzyFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>
            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="button-menu">
                <BsEmojiDizzyFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem>
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
                <S.Item>item 4</S.Item>
                <S.Item>item 5</S.Item>
                <S.Item>item 6</S.Item>
                <S.Item>item 7</S.Item>
                <S.Item>item 8</S.Item>
                <S.Item>item 9</S.Item>
                <S.Item>item 10</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>

          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiExpressionlessFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>
            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="button-menu">
                <BsEmojiExpressionlessFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem>
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
                <S.Item>item 4</S.Item>
                <S.Item>item 5</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>

          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiFrownFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>
            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="button-menu">
                <BsEmojiFrownFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem>
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
                <S.Item>item 4</S.Item>
                <S.Item>item 5</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>

          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiHeartEyesFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>
            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="button-menu">
                <BsEmojiHeartEyesFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem>
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
                <S.Item>item 4</S.Item>
                <S.Item>item 5</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>

          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiLaughingFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>

            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="button-menu">
                <BsEmojiLaughingFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem>
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
                <S.Item>item 4</S.Item>
                <S.Item>item 5</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>

          <S.Menu aria-label="menu">
            <S.ButtonMenu aria-label="button-menu">
              <BsEmojiNeutralFill size={30} />
              <S.ButtonText>menu</S.ButtonText>
            </S.ButtonMenu>
            <S.HiddenMenu aria-label="hidden-menu">
              <S.ButtonMenu aria-label="button-menu">
                <BsEmojiNeutralFill size={30} />
                menu
              </S.ButtonMenu>
              <S.MenuItem>
                <S.Item>item 1</S.Item>
                <S.Item>item 2</S.Item>
                <S.Item>item 3</S.Item>
                <S.Item>item 4</S.Item>
                <S.Item>item 5</S.Item>
              </S.MenuItem>
            </S.HiddenMenu>
          </S.Menu>
        </S.MenuContainer>
      </S.NavBar>

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </S.Container>
  );
};

export default Home;
